import * as vscode from "vscode";
import {
  ParsedParameter,
  ParsedRoute,
  generateFakeData,
} from "mocknest-core";
import type { RouteTreeProvider } from "../providers/routeTreeProvider";

interface ContractTestCase {
  name: string;
  method: string;
  path: string;
  expectedStatus: number;
  headers?: Record<string, string>;
  body?: unknown;
}

export async function generateContractTestSuiteCommand(
  routeTreeProvider: RouteTreeProvider,
): Promise<void> {
  const routes = routeTreeProvider.getRoutes();
  if (routes.length === 0) {
    vscode.window.showInformationMessage(
      "No MockNest routes loaded. Select an OpenAPI spec or start the mock server first.",
    );
    return;
  }

  const port = vscode.workspace
    .getConfiguration("mocknest")
    .get<number>("port", 3001);
  const content = buildContractTestSuite({
    routes,
    baseUrl: `http://localhost:${port}`,
    generatedAt: new Date(),
  });

  const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri;
  const defaultUri = workspaceRoot
    ? vscode.Uri.joinPath(workspaceRoot, "mocknest.contract.test.js")
    : undefined;

  const fileUri = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { JavaScript: ["js"] },
    title: "Generate MockNest Contract Test Suite",
  });

  if (!fileUri) {
    return;
  }

  await vscode.workspace.fs.writeFile(fileUri, Buffer.from(content, "utf-8"));
  const action = await vscode.window.showInformationMessage(
    `Generated ${routes.length} contract smoke test(s).`,
    "Open File",
  );
  if (action === "Open File") {
    const document = await vscode.workspace.openTextDocument(fileUri);
    await vscode.window.showTextDocument(document, { preview: false });
  }
}

export function buildContractTestSuite(options: {
  routes: ParsedRoute[];
  baseUrl: string;
  generatedAt: Date;
}): string {
  const testCases = options.routes.map(createContractTestCase);

  return [
    "/*",
    " * Generated by MockNest.",
    ` * Generated at: ${options.generatedAt.toISOString()}`,
    " *",
    " * Run:",
    " *   node --test mocknest.contract.test.js",
    " *",
    " * Override the target API:",
    ` *   MOCKNEST_BASE_URL=${options.baseUrl} node --test mocknest.contract.test.js`,
    " */",
    "",
    'const test = require("node:test");',
    'const assert = require("node:assert/strict");',
    "",
    `const baseUrl = process.env.MOCKNEST_BASE_URL || ${JSON.stringify(options.baseUrl)};`,
    `const requests = ${JSON.stringify(testCases, null, 2)};`,
    "",
    "for (const request of requests) {",
    "  test(`${request.method} ${request.path} -> ${request.expectedStatus}`, async () => {",
    "    const headers = { ...(request.headers || {}) };",
    "    if (!hasHeader(headers, \"connection\")) {",
    "      headers.Connection = \"close\";",
    "    }",
    "    const init = { method: request.method, headers };",
    "",
    "    if (request.body !== undefined && ![\"GET\", \"HEAD\"].includes(request.method)) {",
    "      if (!hasHeader(headers, \"content-type\")) {",
    "        headers[\"Content-Type\"] = \"application/json\";",
    "      }",
    "      init.body = JSON.stringify(request.body);",
    "    }",
    "",
    "    const response = await fetch(new URL(request.path, normalizeBaseUrl(baseUrl)), init);",
    "    const responseText = await response.text();",
    "    assert.equal(",
    "      response.status,",
    "      request.expectedStatus,",
    "      `Expected ${request.expectedStatus}, got ${response.status}. Body: ${responseText.slice(0, 500)}`,",
    "    );",
    "  });",
    "}",
    "",
    "function hasHeader(headers, name) {",
    "  const target = name.toLowerCase();",
    "  return Object.keys(headers).some((key) => key.toLowerCase() === target);",
    "}",
    "",
    "function normalizeBaseUrl(value) {",
    "  return value.endsWith(\"/\") ? value : `${value}/`;",
    "}",
    "",
  ].join("\n");
}

function createContractTestCase(route: ParsedRoute): ContractTestCase {
  const method = route.method.toUpperCase();
  const headers = createRequiredHeaders(route.parameters);
  const body = createRequestBody(route, method);
  const testCase: ContractTestCase = {
    name: route.summary || `${method} ${route.path}`,
    method,
    path: createRequestPath(route),
    expectedStatus: route.statusCode,
  };

  if (Object.keys(headers).length > 0) {
    testCase.headers = headers;
  }
  if (body !== undefined) {
    testCase.body = body;
  }

  return testCase;
}

function createRequestPath(route: ParsedRoute): string {
  const parameters = route.parameters ?? [];
  const path = hydratePath(route.path, parameters);
  const query = createRequiredQuery(parameters);
  const queryString = new URLSearchParams(query).toString();
  return queryString ? `${path}?${queryString}` : path;
}

function hydratePath(path: string, parameters: ParsedParameter[]): string {
  const pathParameters = parameters.filter((parameter) => parameter.in === "path");
  if (pathParameters.length === 0) {
    return path;
  }

  return path.replace(/:("[^"]+"|[A-Za-z0-9_$]+)/g, (match, rawName: string) => {
    const name = normalizeExpressParameterName(rawName);
    const parameter = pathParameters.find((item) => item.name === name);
    return encodeURIComponent(
      sampleParameterValue(parameter ?? { name, in: "path", required: true }),
    );
  });
}

function createRequiredQuery(
  parameters: ParsedParameter[],
): Record<string, string> {
  const query: Record<string, string> = {};
  for (const parameter of parameters) {
    if (parameter.in !== "query" || !parameter.required) {
      continue;
    }
    query[parameter.name] = sampleParameterValue(parameter);
  }
  return query;
}

function createRequiredHeaders(
  parameters: ParsedParameter[] | undefined,
): Record<string, string> {
  const headers: Record<string, string> = {};
  for (const parameter of parameters ?? []) {
    if (parameter.in !== "header" || !parameter.required) {
      continue;
    }
    headers[parameter.name] = sampleParameterValue(parameter);
  }
  return headers;
}

function createRequestBody(
  route: ParsedRoute,
  method: string,
): unknown | undefined {
  if (method === "GET" || method === "HEAD" || !route.requestSchema) {
    return undefined;
  }

  try {
    return generateFakeData(route.requestSchema);
  } catch {
    return route.requestRequired ? {} : undefined;
  }
}

function sampleParameterValue(parameter: Partial<ParsedParameter>): string {
  const schema = parameter.schema;
  if (schema && !isReferenceObject(schema)) {
    const schemaExtras = schema as Record<string, unknown>;
    if (schema.example !== undefined) {
      return String(schema.example);
    }
    if (schema.default !== undefined) {
      return String(schema.default);
    }
    if (Array.isArray(schemaExtras.enum) && schemaExtras.enum.length > 0) {
      return String(schemaExtras.enum[0]);
    }
    if (schema.type === "integer" || schema.type === "number") {
      return "1";
    }
    if (schema.type === "boolean") {
      return "true";
    }
  }

  if (parameter.name?.toLowerCase().includes("id")) {
    return "sample-id";
  }

  return "sample";
}

function normalizeExpressParameterName(rawName: string): string {
  if (rawName.startsWith('"') && rawName.endsWith('"')) {
    return rawName.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, "\\");
  }
  return rawName;
}

function isReferenceObject(value: unknown): value is { $ref: string } {
  return Boolean(
    value &&
      typeof value === "object" &&
      "$ref" in (value as Record<string, unknown>),
  );
}
