import * as vscode from "vscode";
import type { RequestLogEntry } from "../providers/requestLogProvider";

interface ReplayTestCase {
  name: string;
  method: string;
  path: string;
  expectedStatus: number;
  capturedAt: string;
  headers?: Record<string, string>;
  body?: unknown;
  expectedBody?: unknown;
  expectedShape?: unknown;
}

const SENSITIVE_HEADER_NAMES = new Set([
  "accept-encoding",
  "authorization",
  "connection",
  "content-length",
  "cookie",
  "host",
  "proxy-authorization",
  "set-cookie",
  "user-agent",
  "x-api-key",
  "x-amz-security-token",
]);

export async function generateTrafficReplayTestSuiteCommand(
  entries: RequestLogEntry[],
): Promise<void> {
  if (entries.length === 0) {
    vscode.window.showInformationMessage(
      "No request log entries available. Send traffic through MockNest first.",
    );
    return;
  }

  const port = vscode.workspace
    .getConfiguration("mocknest")
    .get<number>("port", 3001);
  const content = buildTrafficReplayTestSuite({
    entries,
    baseUrl: `http://localhost:${port}`,
    generatedAt: new Date(),
  });

  const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri;
  const defaultUri = workspaceRoot
    ? vscode.Uri.joinPath(workspaceRoot, "mocknest.replay.test.js")
    : undefined;

  const fileUri = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { JavaScript: ["js"] },
    title: "Generate MockNest Traffic Replay Test Suite",
  });

  if (!fileUri) {
    return;
  }

  await vscode.workspace.fs.writeFile(fileUri, Buffer.from(content, "utf-8"));
  const action = await vscode.window.showInformationMessage(
    `Generated ${entries.length} traffic replay test(s).`,
    "Open File",
  );
  if (action === "Open File") {
    const document = await vscode.workspace.openTextDocument(fileUri);
    await vscode.window.showTextDocument(document, { preview: false });
  }
}

export function buildTrafficReplayTestSuite(options: {
  entries: RequestLogEntry[];
  baseUrl: string;
  generatedAt: Date;
}): string {
  const testCases = sortChronologically(options.entries).map(createReplayTestCase);

  return [
    "/*",
    " * Generated by MockNest.",
    ` * Generated at: ${options.generatedAt.toISOString()}`,
    ` * Captured requests: ${testCases.length}`,
    " *",
    " * Run:",
    " *   node --test mocknest.replay.test.js",
    " *",
    " * Override the target API:",
    ` *   MOCKNEST_BASE_URL=${options.baseUrl} node --test mocknest.replay.test.js`,
    " *",
    " * Assert exact captured response bodies:",
    " *   MOCKNEST_REPLAY_STRICT_BODY=1 node --test mocknest.replay.test.js",
    " */",
    "",
    'const test = require("node:test");',
    'const assert = require("node:assert/strict");',
    "",
    `const baseUrl = process.env.MOCKNEST_BASE_URL || ${JSON.stringify(options.baseUrl)};`,
    'const strictBody = process.env.MOCKNEST_REPLAY_STRICT_BODY === "1";',
    `const requests = ${JSON.stringify(testCases, null, 2)};`,
    "",
    'test("replays captured MockNest traffic in order", async (t) => {',
    "  for (const [index, request] of requests.entries()) {",
    "    await t.test(`${index + 1}. ${request.name}`, async () => {",
    "      const headers = { ...(request.headers || {}) };",
    '      if (!hasHeader(headers, "connection")) {',
    '        headers.Connection = "close";',
    "      }",
    "      const init = { method: request.method, headers };",
    "",
    '      if (request.body !== undefined && !["GET", "HEAD"].includes(request.method)) {',
    '        if (!hasHeader(headers, "content-type")) {',
    '          headers["Content-Type"] = "application/json";',
    "        }",
    "        init.body = JSON.stringify(request.body);",
    "      }",
    "",
    "      const response = await fetch(new URL(request.path, normalizeBaseUrl(baseUrl)), init);",
    "      const responseText = await response.text();",
    "      const responseBody = parseBody(responseText);",
    "",
    "      assert.equal(",
    "        response.status,",
    "        request.expectedStatus,",
    "        `Expected ${request.expectedStatus}, got ${response.status}. Body: ${responseText.slice(0, 500)}`,",
    "      );",
    "",
    "      if (request.expectedBody !== undefined) {",
    "        if (strictBody) {",
    "          assert.deepEqual(",
    "            responseBody,",
    "            request.expectedBody,",
    "            `Response body changed for ${request.method} ${request.path}.`,",
    "          );",
    "        } else {",
    "          assert.deepEqual(",
    "            createShape(responseBody),",
    "            request.expectedShape,",
    "            `Response shape changed for ${request.method} ${request.path}. Set MOCKNEST_REPLAY_STRICT_BODY=1 to enforce exact captured bodies.`,",
    "          );",
    "        }",
    "      }",
    "    });",
    "  }",
    "});",
    "",
    "function hasHeader(headers, name) {",
    "  const target = name.toLowerCase();",
    "  return Object.keys(headers).some((key) => key.toLowerCase() === target);",
    "}",
    "",
    "function normalizeBaseUrl(value) {",
    "  return value.endsWith(\"/\") ? value : `${value}/`;",
    "}",
    "",
    "function parseBody(text) {",
    "  if (text.length === 0) {",
    "    return undefined;",
    "  }",
    "  try {",
    "    return JSON.parse(text);",
    "  } catch {",
    "    return text;",
    "  }",
    "}",
    "",
    "function createShape(value) {",
    "  if (value === null) {",
    '    return "null";',
    "  }",
    "  if (Array.isArray(value)) {",
    "    return {",
    '      type: "array",',
    "      items: value.length > 0 ? createShape(value[0]) : undefined,",
    "    };",
    "  }",
    '  if (typeof value === "object") {',
    "    return {",
    '      type: "object",',
    "      properties: Object.fromEntries(",
    "        Object.keys(value)",
    "          .sort()",
    "          .map((key) => [key, createShape(value[key])]),",
    "      ),",
    "    };",
    "  }",
    "  return typeof value;",
    "}",
    "",
  ].join("\n");
}

function createReplayTestCase(entry: RequestLogEntry): ReplayTestCase {
  const method = entry.method.toUpperCase();
  const headers = normalizeReplayHeaders(entry.requestHeaders);
  const testCase: ReplayTestCase = {
    name: `${method} ${entry.path} -> ${entry.statusCode}`,
    method,
    path: entry.path,
    expectedStatus: entry.statusCode,
    capturedAt: entry.timestamp,
  };

  if (Object.keys(headers).length > 0) {
    testCase.headers = headers;
  }
  if (entry.requestBody !== undefined && requestCanHaveBody(method)) {
    testCase.body = entry.requestBody;
  }
  if (entry.responseBody !== undefined) {
    testCase.expectedBody = entry.responseBody;
    testCase.expectedShape = createShape(entry.responseBody);
  }

  return testCase;
}

function sortChronologically(entries: RequestLogEntry[]): RequestLogEntry[] {
  return [...entries].sort((left, right) => {
    const leftTime = new Date(left.timestamp).getTime();
    const rightTime = new Date(right.timestamp).getTime();
    if (Number.isNaN(leftTime) || Number.isNaN(rightTime)) {
      return Number(left.id) - Number(right.id);
    }
    return leftTime - rightTime;
  });
}

function normalizeReplayHeaders(
  headers: RequestLogEntry["requestHeaders"],
): Record<string, string> {
  if (!headers) {
    return {};
  }

  const replayHeaders: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers)) {
    const normalizedKey = key.toLowerCase();
    if (SENSITIVE_HEADER_NAMES.has(normalizedKey)) {
      continue;
    }
    if (normalizedKey.startsWith("x-mock-")) {
      continue;
    }
    if (value === undefined || value === null) {
      continue;
    }
    replayHeaders[key] = Array.isArray(value) ? value.map(String).join(", ") : String(value);
  }
  return replayHeaders;
}

function requestCanHaveBody(method: string): boolean {
  return !["GET", "HEAD"].includes(method.toUpperCase());
}

function createShape(value: unknown): unknown {
  if (value === null) {
    return "null";
  }

  if (Array.isArray(value)) {
    return {
      type: "array",
      items: value.length > 0 ? createShape(value[0]) : undefined,
    };
  }

  if (typeof value === "object") {
    return {
      type: "object",
      properties: Object.fromEntries(
        Object.keys(value as Record<string, unknown>)
          .sort()
          .map((key) => [
            key,
            createShape((value as Record<string, unknown>)[key]),
          ]),
      ),
    };
  }

  return typeof value;
}
